### ISSUE TITLE
没法运行项目

### ISSUE THREAD

**Issue by lycaste** [vikingmute/webpack-react-kit#7]
node版本是6.3

npm run dev

> webpack-react-kit@1.0.0 dev /Users/yh/我的坚果云/code/webpack-react-kit
> node server.js

module.js:442
    throw err;
    ^

Error: Cannot find module 'webpack-dev-server'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/yh/我的坚果云/code/webpack-react-kit/server.js:2:24)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! webpack-react-kit@1.0.0 dev: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack-react-kit@1.0.0 dev script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-react-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-react-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-react-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/yh/我的坚果云/code/webpack-react-kit/npm-debug.log

**Comment by theewind** [comment]
npm i

**Comment by vikingmute** [comment]
@lycaste 已经把webpack-dev-server 添加到dep里面了 现在应该好了
