### ISSUE TITLE
不能运行项目

### ISSUE THREAD

**Issue by Boboandhaifeng** [vikingmute/webpack-react-kit#8]
$ node -v
v6.3.0

$ npm run dev

> webpack-react-kit@1.0.0 dev F:\react_abc\book_react_quanzhan\jiaoshoujia\webpack-react-kit
> node server.js

E:\node\node_cache\webpack-dev-server:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\react_abc\book_react_quanzhan\jiaoshoujia\webpack-react-kit\server.js:2:24)
    at Module._compile (module.js:541:32)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "E:\\node\\node.exe" "E:\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! webpack-react-kit@1.0.0 dev: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-react-kit@1.0.0 dev script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-react-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-react-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-react-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\react_abc\book_react_quanzhan\jiaoshoujia\webpack-react-kit\npm-debug.log

**Comment by Boboandhaifeng** [comment]
node 版本太高  更换为 6.2.0 稳定版

**Comment by vikingmute** [comment]
@Boboandhaifeng 我用6.5 做了测试 发现没问题， 我把package.json 里面添加了 webpack－dev－server 你可以重新安装试一试
